# Generated by Django 5.1.3 on 2024-11-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glaucoma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimage',
            name='date_taken',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='image',
            field=models.BinaryField(),
        ),
    ]
