# Generated by Django 5.1.3 on 2024-12-02 23:37

from django.db import migrations


def populate_test_data(apps, schema_editor):
    # SQL to insert test data into glaucoma_doctor table
    sql_doctor = """
    INSERT INTO glaucoma_doctor (first_name, last_name, username, password)
    VALUES 
    ('Jan', 'Kowalski', 'jkowalski', 'haslo123'),
    ('Anna', 'Nowak', 'anowak', 'anna2023'),
    ('Michał', 'Wiśniewski', 'mwisniewski', 'bezpieczneHaslo!'),
    ('Zofia', 'Kaczmarek', 'zkaczmarek', 'kaczmarek2024');
    """
    
    # SQL to insert test data into glaucoma_patient table
    sql_patient = """
    INSERT INTO glaucoma_patient (first_name, last_name, date_of_birth, gender)
    VALUES 
    ('Katarzyna', 'Lewandowska', '1990-05-12', 'kobieta'),
    ('Piotr', 'Zieliński', '1985-11-23', 'mężczyzna'),
    ('Agnieszka', 'Dąbrowska', '1992-03-18', 'kobieta'),
    ('Tomasz', 'Mazur', '1978-07-09', 'mężczyzna'),
    ('Marek', 'Kwiatkowski', '1987-09-15', 'mężczyzna'),
    ('Ewa', 'Wójcik', '1995-01-20', 'kobieta'),
    ('Adam', 'Kaczmarek', '1990-06-11', 'mężczyzna'),
    ('Olga', 'Jankowska', '1982-12-05', 'kobieta'),
    ('Wojciech', 'Sikora', '1979-08-30', 'mężczyzna'),
    ('Julia', 'Czajka', '1993-11-17', 'kobieta'),
    ('Rafał', 'Kowalewski', '1983-02-03', 'mężczyzna'),
    ('Magdalena', 'Jóźwiak', '1991-07-25', 'kobieta'),
    ('Patryk', 'Bąk', '1988-04-02', 'mężczyzna'),
    ('Justyna', 'Pawlak', '1994-10-12', 'kobieta'),
    ('Andrzej', 'Nowicki', '1986-09-07', 'mężczyzna');
    """
    
    # Execute the insert queries
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute(sql_doctor)
        cursor.execute(sql_patient)


class Migration(migrations.Migration):

    dependencies = [
        ('glaucoma', '0002_alter_patientimage_date_taken_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_test_data),
    ]
