# Generated by Django 5.1.3 on 2024-12-08 21:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glaucoma', '0003_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='patient_images/'), upload_to='patient_images/'),
        ),
    ]
