# Generated by Django 5.1.3 on 2024-12-09 22:29

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glaucoma', '0004_alter_patientimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/glaucoma_project/media')), upload_to='patient_images/'),
        ),
    ]
