# Generated by Django 5.1.3 on 2025-03-07 18:21

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glaucoma', '0005_alter_patientimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/Veronika/glaukoma/glaucoma_project/media')), upload_to='patient_images/'),
        ),
    ]
