# Generated by Django 5.1.3 on 2025-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glaucoma', '0006_alter_patientimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorimageanalysis',
            name='cdr_points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
