# Generated by Django 5.2 on 2025-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glaucoma', '0007_doctorimageanalysis_cdr_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorimageanalysis',
            name='grade',
            field=models.IntegerField(choices=[(0, 'Healthy'), (1, 'No Diagnosis'), (2, 'Glaucoma')], null=True),
        ),
    ]
