# Generated by Django 5.1.3 on 2025-06-03 22:54

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glaucoma', '0008_alter_doctorimageanalysis_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorimageanalysis',
            name='grade',
            field=models.IntegerField(choices=[(0, 'Healthy'), (1, 'No Diagnosis'), (2, 'Glaucoma')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/glaucoma_project/media')), upload_to='patient_images/'),
        ),
    ]
